name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest testit-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # Stop build on critical syntax errors
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Treat other issues as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests and upload results to TestIt
      run: |
        mkdir -p reports
        pytest --testit --junitxml=reports/results.xml

        export TMS_TOKEN=${{ secrets.TMS_TOKEN }}

        testit results import \
          --url https://team-hawh.testit.software/ \
          --project-id 5236eb3f-7c05-46f9-a609-dc0278896464 \
          --configuration-id 15dbb164-c1aa-4cbf-830c-8c01ae14f4fb \
          --testrun-name "Pytest test run" \
          --results reports
          
